//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormalAccessory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormalAccessory()
        {
            this.FormalOutfits = new HashSet<FormalOutfit>();
        }
    
        public int FormalAccessoryID { get; set; }
        public string FormalAccessoryName { get; set; }
        public string FormalAccessoryPhoto { get; set; }
        public string FormalAccessoryColor { get; set; }
        public string FormalAccessorySeason { get; set; }
        public string FormalAccessoryOccasion { get; set; }
        public string FormalAccessoryType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormalOutfit> FormalOutfits { get; set; }
    }
}
