//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormalBottom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormalBottom()
        {
            this.FormalOutfits = new HashSet<FormalOutfit>();
        }
    
        public int FormalBottomID { get; set; }
        public string FormalBottomName { get; set; }
        public string FormalBottomPhoto { get; set; }
        public string FormalBottomColor { get; set; }
        public string FormalBottomSeason { get; set; }
        public string FormalBottomOccasion { get; set; }
        public string FormalBottomType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormalOutfit> FormalOutfits { get; set; }
    }
}
