//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormalSho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormalSho()
        {
            this.FormalOutfits = new HashSet<FormalOutfit>();
        }
    
        public int FormalShoesID { get; set; }
        public string FormalShoesName { get; set; }
        public string FormalShoesPhoto { get; set; }
        public string FormalShoesColor { get; set; }
        public string FormalShoesSeason { get; set; }
        public string FormalShoesOccasion { get; set; }
        public string FormalShoesType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormalOutfit> FormalOutfits { get; set; }
    }
}
