//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormalTop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormalTop()
        {
            this.FormalOutfits = new HashSet<FormalOutfit>();
        }
    
        public int FormalTopID { get; set; }
        public string FormalTopName { get; set; }
        public string FormalTopPhoto { get; set; }
        public string FormalTopColor { get; set; }
        public string FormalTopSeason { get; set; }
        public string FormalTopOccasion { get; set; }
        public string FormalTopType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormalOutfit> FormalOutfits { get; set; }
    }
}
