//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformalTop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformalTop()
        {
            this.InformalOutfits = new HashSet<InformalOutfit>();
        }
    
        public int InformalTopID { get; set; }
        public string InformalTopName { get; set; }
        public string InformalTopPhoto { get; set; }
        public string InformalTopColor { get; set; }
        public string InformalTopSeason { get; set; }
        public string InformalTopOccasion { get; set; }
        public string InformalTopType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformalOutfit> InformalOutfits { get; set; }
    }
}
