//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformalAccessory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformalAccessory()
        {
            this.InformalOutfits = new HashSet<InformalOutfit>();
        }
    
        public int InformalAccessoryID { get; set; }
        public string InformalAccessoryName { get; set; }
        public string InformalAccessoryPhoto { get; set; }
        public string InformalAccessoryColor { get; set; }
        public string InformalAccessorySeason { get; set; }
        public string InformalAccessoryOccasion { get; set; }
        public string InformalAccessoryType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformalOutfit> InformalOutfits { get; set; }
    }
}
