//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformalOutfit
    {
        public int InformalOutfitID { get; set; }
        public int MainOutfitID { get; set; }
        public int InformalTopID { get; set; }
        public int InformalBottomID { get; set; }
        public int InformalShoesID { get; set; }
        public int InformalAccessoryID { get; set; }
    
        public virtual InformalAccessory InformalAccessory { get; set; }
        public virtual InformalBottom InformalBottom { get; set; }
        public virtual InformalSho InformalSho { get; set; }
        public virtual InformalTop InformalTop { get; set; }
        public virtual Outfit Outfit { get; set; }
    }
}
