//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformalBottom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformalBottom()
        {
            this.InformalOutfits = new HashSet<InformalOutfit>();
        }
    
        public int InformalBottomID { get; set; }
        public string InformalBottomName { get; set; }
        public string InformalBottomPhoto { get; set; }
        public string InformalBottomColor { get; set; }
        public string InformalBottomSeason { get; set; }
        public string InformalBottomOccasion { get; set; }
        public string InformalBottomType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformalOutfit> InformalOutfits { get; set; }
    }
}
