//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformalSho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformalSho()
        {
            this.InformalOutfits = new HashSet<InformalOutfit>();
        }
    
        public int InformalShoesID { get; set; }
        public string InformalShoesName { get; set; }
        public string InformalShoesPhoto { get; set; }
        public string InformalShoesColor { get; set; }
        public string InformalShoesSeason { get; set; }
        public string InformalShoesOccasion { get; set; }
        public string InformalShoesType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformalOutfit> InformalOutfits { get; set; }
    }
}
