//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeisureAccessory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeisureAccessory()
        {
            this.LeisureOutfits = new HashSet<LeisureOutfit>();
        }
    
        public int LeisureAccessoryID { get; set; }
        public string LeisureAccessoryName { get; set; }
        public string LeisureAccessoryPhoto { get; set; }
        public string LeisureAccessoryColor { get; set; }
        public string LeisureAccessorySeason { get; set; }
        public string LeisureAccessoryOccasion { get; set; }
        public string LeisureAccessoryType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeisureOutfit> LeisureOutfits { get; set; }
    }
}
