//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeisureBottom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeisureBottom()
        {
            this.LeisureOutfits = new HashSet<LeisureOutfit>();
        }
    
        public int LeisureBottomID { get; set; }
        public string LeisureBottomName { get; set; }
        public string LeisureBottomPhoto { get; set; }
        public string LeisureBottomColor { get; set; }
        public string LeisureBottomSeason { get; set; }
        public string LeisureBottomOccasion { get; set; }
        public string LeisureBottomType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeisureOutfit> LeisureOutfits { get; set; }
    }
}
