//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeisureOutfit
    {
        public int LeisureOutfitID { get; set; }
        public int MainOutfitID { get; set; }
        public int LeisureTopID { get; set; }
        public int LeisureBottomID { get; set; }
        public int LeisureShoesID { get; set; }
        public int LeisureAccessoryID { get; set; }
    
        public virtual LeisureAccessory LeisureAccessory { get; set; }
        public virtual LeisureBottom LeisureBottom { get; set; }
        public virtual LeisureSho LeisureSho { get; set; }
        public virtual LeisureTop LeisureTop { get; set; }
        public virtual Outfit Outfit { get; set; }
    }
}
