//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeisureSho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeisureSho()
        {
            this.LeisureOutfits = new HashSet<LeisureOutfit>();
        }
    
        public int LeisureShoesID { get; set; }
        public string LeisureShoesName { get; set; }
        public string LeisureShoesPhoto { get; set; }
        public string LeisureShoesColor { get; set; }
        public string LeisureShoesSeason { get; set; }
        public string LeisureShoesOccasion { get; set; }
        public string LeisureShoesType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeisureOutfit> LeisureOutfits { get; set; }
    }
}
