//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCWardrobeEntities : DbContext
    {
        public MVCWardrobeEntities()
            : base("name=MVCWardrobeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FormalAccessory> FormalAccessories { get; set; }
        public virtual DbSet<FormalBottom> FormalBottoms { get; set; }
        public virtual DbSet<FormalOutfit> FormalOutfits { get; set; }
        public virtual DbSet<FormalSho> FormalShoes { get; set; }
        public virtual DbSet<FormalTop> FormalTops { get; set; }
        public virtual DbSet<InformalAccessory> InformalAccessories { get; set; }
        public virtual DbSet<InformalBottom> InformalBottoms { get; set; }
        public virtual DbSet<InformalOutfit> InformalOutfits { get; set; }
        public virtual DbSet<InformalSho> InformalShoes { get; set; }
        public virtual DbSet<InformalTop> InformalTops { get; set; }
        public virtual DbSet<LeisureAccessory> LeisureAccessories { get; set; }
        public virtual DbSet<LeisureBottom> LeisureBottoms { get; set; }
        public virtual DbSet<LeisureOutfit> LeisureOutfits { get; set; }
        public virtual DbSet<LeisureSho> LeisureShoes { get; set; }
        public virtual DbSet<LeisureTop> LeisureTops { get; set; }
        public virtual DbSet<Outfit> Outfits { get; set; }
        public virtual DbSet<WorkAccessory> WorkAccessories { get; set; }
        public virtual DbSet<WorkBottom> WorkBottoms { get; set; }
        public virtual DbSet<WorkOutfit> WorkOutfits { get; set; }
        public virtual DbSet<WorkSho> WorkShoes { get; set; }
        public virtual DbSet<WorkTop> WorkTops { get; set; }
    }
}
