//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkTop()
        {
            this.WorkOutfits = new HashSet<WorkOutfit>();
        }
    
        public int WorkTopID { get; set; }
        public string WorkTopName { get; set; }
        public string WorkTopPhoto { get; set; }
        public string WorkTopColor { get; set; }
        public string WorkTopSeason { get; set; }
        public string WorkTopOccasion { get; set; }
        public string WorkTopType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOutfit> WorkOutfits { get; set; }
    }
}
