//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkBottom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkBottom()
        {
            this.WorkOutfits = new HashSet<WorkOutfit>();
        }
    
        public int WorkBottomID { get; set; }
        public string WorkBottomName { get; set; }
        public string WorkBottomPhoto { get; set; }
        public string WorkBottomColor { get; set; }
        public string WorkBottomSeason { get; set; }
        public string WorkBottomOccasion { get; set; }
        public string WorkBottomType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOutfit> WorkOutfits { get; set; }
    }
}
