//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkSho()
        {
            this.WorkOutfits = new HashSet<WorkOutfit>();
        }
    
        public int WorkShoesID { get; set; }
        public string WorkShoesName { get; set; }
        public string WorkShoesPhoto { get; set; }
        public string WorkShoesColor { get; set; }
        public string WorkShoesSeason { get; set; }
        public string WorkShoesOccasion { get; set; }
        public string WorkShoesType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOutfit> WorkOutfits { get; set; }
    }
}
