//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkAccessory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkAccessory()
        {
            this.WorkOutfits = new HashSet<WorkOutfit>();
        }
    
        public int WorkAccessoryID { get; set; }
        public string WorkAccessoryName { get; set; }
        public string WorkAccessoryPhoto { get; set; }
        public string WorkAccessoryColor { get; set; }
        public string WorkAccessorySeason { get; set; }
        public string WorkAccessoryOccasion { get; set; }
        public string WorkAccessoryType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOutfit> WorkOutfits { get; set; }
    }
}
