//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOutfit
    {
        public int WorkOutfitID { get; set; }
        public int MainOutfitID { get; set; }
        public int WorkTopID { get; set; }
        public int WorkBottomID { get; set; }
        public int WorkShoesID { get; set; }
        public int WorkAccessoryID { get; set; }
    
        public virtual Outfit Outfit { get; set; }
        public virtual WorkAccessory WorkAccessory { get; set; }
        public virtual WorkBottom WorkBottom { get; set; }
        public virtual WorkSho WorkSho { get; set; }
        public virtual WorkTop WorkTop { get; set; }
    }
}
